### ISSUE TITLE
when git cloning music-os-core, node_modules of src/strategies are probably not automatically installed. Automate

### ISSUE THREAD

**Issue by TimDaub** [neume-network/core#34]

**Comment by naiknareshh** [comment]
This can be fixed by adding **postinstall** script into package.json -

 "scripts": {
    **"postinstall": "cd ./src/strategies && npm install",**
    "test": "ava --verbose --timeout=20s",
    "dev": "DEBUG=music-os-core:* node ./src/boot.mjs",
    "dev:silent": "node ./src/boot.mjs",
    "prepare": "husky install"
  },

I can create a PR if you assign this issue to me.

**Comment by TimDaub** [comment]
sounds good!
