### ISSUE TITLE
add pull request template

### ISSUE THREAD

**Issue by victoriacheng15** [neume-network/core#43]
Check this [doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for more information. This is to provide a list of what information you need from contributors.

You can also add keyword to close issue. So that way the maintainers don't have to go back to the issue and close it. See [info](https://docs.devart.com/studio-for-sql-server/source-controlling-databases/associating-commits-with-github-issues.html) here

```
close #(number)
```
replace (number) with the issue number

**Comment by TimDaub** [comment]
@victoriacheng15, sure feel free to add it!
