### ISSUE TITLE
Should we move to a monorepo?

### ISSUE THREAD

**Issue by il3ven** [neume-network/core#44]
We have multiple packages: core, strategies, message-schema, extractor which we are either imported through npm or through git submodule. 

The problem with importing packages through npm is that for development I have to modify the code in node_modules. If the code works I have to copy it from node_modules to the actual repo in order to make a pull request. If I made changes across multiple packages. It can cause multiple pull requests for the same feature across multiple repos. Which can be hard to track imo.

The problem with submodules is that they are a little confusing. At least, in my opinion. The problem of multiple PRs across repos for the same feature is a problem with submodules too.

Monorepo architecture is gaining popularity. For example, [jest](https://github.com/facebook/jest) is a monorepo.

Since version 8, npm supports monorepo [out of the box](https://docs.npmjs.com/cli/v8/using-npm/workspaces) so theoretically we won't be introducing any new tools.

**Comment by TimDaub** [comment]
We can leave this open but generally the process we have is good as it enables separation of concern not only for managing source code but also, git tags, issues, prs and ci. Monorepo is a can of worms I don't wanna open at this point as I want to focus on functionality.

**Comment by TimDaub** [comment]
> The problem with importing packages through npm is that for development I have to modify the code in node_modules. If the code works I have to copy it from node_modules to the actual repo in order to make a pull request.

U can temporarily link modules using `npm link`.
