### ISSUE TITLE
src/strategies submodule subproject commit id is lagging

### ISSUE THREAD

**Issue by morestatic** [neume-network/core#52]
It seems that the core src/stategies submodule isn't updating after recent strategies updates. Not quite sure of the root clause of this but it seems that the default branch on clone is a local HEAD branch (which matches the committed core src/strategies subproject commit id). Checking out the 'main' src/strategies branch updates src/strategies to latest and causes an update to the src/strategies subject commit id in the core repo, which then needs to be committed and pushed as an update to github.

It seems that if the core repo is to be kept in-sync with the strategies submodule updates then corresponding core repo updates must made. The updates can diverge but then repo users must make sure to update the submodule each time before use. Sounds like fair practice but it is also an easy step to miss or forget.

Note: submodules are not really my area so caveat the above with this in mind.

**Comment by TimDaub** [comment]
> Checking out the 'main' src/strategies branch updates src/strategies to latest and causes an update to the src/strategies subject commit id in the core repo, which then needs to be committed and pushed as an update to github.

correct

Yeah this is starting to become a problem for everyone wanting to on-board. I'm not entirely sure how to resolve this. It seems at least for now, having a note in the repository's readme installation instruction that `src/strategies` should always point to the latest commit would be an improvement.

Generally, I just want to make sure that we separate the strategies from the core repository. But the question is how we do that. I'll think a bit more about this and for now leave this issue open. @il3ven also had thoughts on this.

**Comment by TimDaub** [comment]
Since we're now periodically cloning neume-network/core in neume-network/data to run the crawl periodically, I assume this problem will become less and less significant as we now have an interest to keep neume-network/core and neume-network/strategies in sync.
