### ISSUE TITLE
All usages of web3subgraph in crawlpath must be renamed to logs-to-subgraph

### ISSUE THREAD

**Issue by TimDaub** [neume-network/core#80]
- this one and others: https://github.com/neume-network/core/blob/83dcf4ca4fd7943935c3c26a7c59569a609c4ebf/crawl_path.mjs#L12
- the first strategy must be call-block-logs followed by logs-to-subgraph

**Comment by TimDaub** [comment]
actually, even better would be where we instruct users to pick and choose a crawl path from https://github.com/neume-network/crawl-path-blueprints

**Comment by il3ven** [comment]
Was fixed in 54ce47e17cc804d587060b443f57d40bd420dc0b
